// File generated by `flutterfire configure` - modified manually
// Project: lythuyet1-32b54

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgXGOZc5QqxDv5gYXQQ_1VqZA6W9V2gNM',
    authDomain: 'lythuyet1-32b54.firebaseapp.com',
    projectId: 'lythuyet1-32b54',
    storageBucket: 'lythuyet1-32b54.firebasestorage.app',
    messagingSenderId: '123456789012',
    appId: '1:123456789012:web:abcdef1234567890',
    databaseURL: 'https://lythuyet1-32b54.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgXGOZc5QqxDv5gYXQQ_1VqZA6W9V2gNM',
    appId: '1:123456789012:android:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'lythuyet1-32b54',
    databaseURL: 'https://lythuyet1-32b54.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgXGOZc5QqxDv5gYXQQ_1VqZA6W9V2gNM',
    appId: '1:123456789012:ios:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'lythuyet1-32b54',
    databaseURL: 'https://lythuyet1-32b54.firebaseio.com',
    iosBundleId: 'com.example.th3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgXGOZc5QqxDv5gYXQQ_1VqZA6W9V2gNM',
    appId: '1:123456789012:macos:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'lythuyet1-32b54',
    databaseURL: 'https://lythuyet1-32b54.firebaseio.com',
    iosBundleId: 'com.example.th3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgXGOZc5QqxDv5gYXQQ_1VqZA6W9V2gNM',
    appId: '1:123456789012:windows:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'lythuyet1-32b54',
    databaseURL: 'https://lythuyet1-32b54.firebaseio.com',
  );
}
